//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEventDetail()
        {
            this.tblEventInvitationInfoes = new HashSet<tblEventInvitationInfo>();
        }
    
        public int ID { get; set; }
        public string UserID { get; set; }
        public string EventTitle { get; set; }
        public string Venue { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEventInvitationInfo> tblEventInvitationInfoes { get; set; }
    }
}
