//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventInvitationInfo
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public string SenderID { get; set; }
        public string InvitedID { get; set; }
        public Nullable<bool> Response { get; set; }
        public string Feedback { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual tblEventDetail tblEventDetail { get; set; }

        public static implicit operator tblEventInvitationInfo(List<tblEventInvitationInfo> v)
        {
            throw new NotImplementedException();
        }
    }
}
